# /webrtc-chat/docker-compose.yml

version: "3.8"

services:
  # 서버 컨테이너
  server:
    build:
      context: ./server # ./server 폴더의 Dockerfile을 사용
      dockerfile: Dockerfile
    container_name: webrtc_server
    ports:
      - "3000:3000" # 서버 포트 (시그널링 등)
    volumes:
      - ./server:/usr/src/app # 로컬 코드와 동기화 (개발 시 유용)
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development

  # 클라이언트 컨테이너 (개발 서버 기준)
  client:
    build:
      context: ./client # ./client 폴더의 Dockerfile을 사용
      dockerfile: Dockerfile
    container_name: webrtc_client
    ports:
      - "8080:8080" # 클라이언트 개발 서버 포트 (예: Vue/React dev server)
    volumes:
      - ./client:/usr/src/app # 로컬 코드와 동기화
      - /usr/src/app/node_modules
    depends_on:
      - server # 서버가 먼저 실행되도록 의존성 설정
